# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5f4e7a4b8af12da48298f257ab048b401c5488c8f88d8a74ead04475898c224b58f41945a66ba5bbe7fbd42a05b339328929cdcf3b2f1b3703bcfa62299b65

test:
  secret_key_base: 2a55a541f3c3c802db5ec2c86d1085a0745903e4e2d12c44ec7daba52a312acf8edb978368c219efa96bd15e290713dc9525d62eaf8ee1e82d2684493a062835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
